# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import grpc.experimental

from . import deepface_pb2 as deepface__pb2


class DeepFaceServiceStub(object):
    """----------------
    DeepFace Service
    ----------------

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Analyze = channel.unary_unary(
                '/deepface.api.proto.DeepFaceService/Analyze',
                request_serializer=deepface__pb2.AnalyzeRequest.SerializeToString,
                response_deserializer=deepface__pb2.AnalyzeResponse.FromString,
                )
        self.Represent = channel.unary_unary(
                '/deepface.api.proto.DeepFaceService/Represent',
                request_serializer=deepface__pb2.RepresentRequest.SerializeToString,
                response_deserializer=deepface__pb2.RepresentResponse.FromString,
                )
        self.Verify = channel.unary_unary(
                '/deepface.api.proto.DeepFaceService/Verify',
                request_serializer=deepface__pb2.VerifyRequest.SerializeToString,
                response_deserializer=deepface__pb2.VerifyResponse.FromString,
                )


class DeepFaceServiceServicer(object):
    """----------------
    DeepFace Service
    ----------------

    """

    def Analyze(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Represent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Verify(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DeepFaceServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Analyze': grpc.unary_unary_rpc_method_handler(
                    servicer.Analyze,
                    request_deserializer=deepface__pb2.AnalyzeRequest.FromString,
                    response_serializer=deepface__pb2.AnalyzeResponse.SerializeToString,
            ),
            'Represent': grpc.unary_unary_rpc_method_handler(
                    servicer.Represent,
                    request_deserializer=deepface__pb2.RepresentRequest.FromString,
                    response_serializer=deepface__pb2.RepresentResponse.SerializeToString,
            ),
            'Verify': grpc.unary_unary_rpc_method_handler(
                    servicer.Verify,
                    request_deserializer=deepface__pb2.VerifyRequest.FromString,
                    response_serializer=deepface__pb2.VerifyResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'deepface.api.proto.DeepFaceService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class DeepFaceService(object):
    """----------------
    DeepFace Service
    ----------------

    """

    @staticmethod
    def Analyze(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/deepface.api.proto.DeepFaceService/Analyze',
            deepface__pb2.AnalyzeRequest.SerializeToString,
            deepface__pb2.AnalyzeResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Represent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/deepface.api.proto.DeepFaceService/Represent',
            deepface__pb2.RepresentRequest.SerializeToString,
            deepface__pb2.RepresentResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Verify(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/deepface.api.proto.DeepFaceService/Verify',
            deepface__pb2.VerifyRequest.SerializeToString,
            deepface__pb2.VerifyResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
