# built-in dependencies
import os
import json
import hashlib
import struct
from typing import Any, Dict, Optional, List, Union, cast

# 3rd party dependencies
import numpy as np

# project dependencies
from deepface.modules.database.types import Database
from deepface.modules.exceptions import DuplicateEntryError
from deepface.commons.logger import Logger

logger = Logger()

# oracle accepts at most 1000 expressions in an IN list
_SEARCH_BY_ID_CHUNK_SIZE = 500

# ORA-00001: unique constraint violated
_UNIQUE_VIOLATION_CODE = 1

# ORA-01031: insufficient privileges
_INSUFFICIENT_PRIVILEGES_CODE = 1031

# oracle does not support CREATE TABLE IF NOT EXISTS before 23ai,
# so existence of tables is checked in user_tables first
CREATE_EMBEDDINGS_TABLE_SQL = """
    CREATE TABLE embeddings (
        id NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
        img_name VARCHAR2(4000) NOT NULL,
        face BLOB NOT NULL,
        face_shape VARCHAR2(64) NOT NULL,
        model_name VARCHAR2(100) NOT NULL,
        detector_backend VARCHAR2(100) NOT NULL,
        aligned NUMBER(1) DEFAULT 1,
        l2_normalized NUMBER(1) DEFAULT 0,
        embedding BLOB NOT NULL,
        created_at TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP,
        face_hash CHAR(64) NOT NULL,
        embedding_hash CHAR(64) NOT NULL,
        CONSTRAINT uq_embeddings_face_embedding UNIQUE (face_hash, embedding_hash)
    )
"""

CREATE_EMBEDDINGS_INDEX_TABLE_SQL = """
    CREATE TABLE embeddings_index (
        id NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
        model_name VARCHAR2(100),
        detector_backend VARCHAR2(100),
        align NUMBER(1),
        l2_normalized NUMBER(1),
        index_data BLOB,
        created_at TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP,
        updated_at TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP,
        CONSTRAINT uq_embeddings_index_config
            UNIQUE (model_name, detector_backend, align, l2_normalized)
    )
"""


def _decode_embedding(embedding_bytes: bytes) -> List[float]:
    """
    Embeddings are stored as little-endian float64 bytes to keep them lossless.
    """
    return cast(List[float], np.frombuffer(embedding_bytes, dtype="<f8").tolist())


def _error_code(error: Exception) -> Optional[int]:
    return getattr(error.args[0], "code", None) if error.args else None


# pylint: disable=too-many-positional-arguments
class OracleClient(Database):
    def __init__(
        self,
        connection_details: Optional[Union[Dict[str, Any], str]] = None,
        connection: Any = None,
    ) -> None:
        # Import here to avoid mandatory dependency
        try:
            import oracledb
        except (ModuleNotFoundError, ImportError) as e:
            raise ValueError(
                "oracledb is an optional dependency, ensure the library is installed."
                "Please install using 'pip install oracledb'"
            ) from e

        self.oracledb = oracledb

        if connection is not None:
            self.conn = connection
        else:
            # Retrieve connection details from parameter or environment variable
            self.conn_details = connection_details or os.environ.get("DEEPFACE_ORACLE_URI")
            if not self.conn_details:
                raise ValueError(
                    "Oracle connection information not found. "
                    "Please provide connection_details or set the DEEPFACE_ORACLE_URI"
                    " environment variable."
                )

            # string is an easy connect string, e.g. user/password@host:1521/service_name
            if isinstance(self.conn_details, str):
                self.conn = self.oracledb.connect(self.conn_details)
            elif isinstance(self.conn_details, dict):
                self.conn = self.oracledb.connect(**self.conn_details)
            else:
                raise ValueError("connection_details must be either a string or a dict.")

        # Ensure the embeddings table exists
        self.initialize_database()

    def _cursor(self) -> Any:
        """
        Create a cursor fetching BLOB columns as bytes instead of LOB locators,
            which would otherwise require an extra round trip per row to read.
        """
        cur = self.conn.cursor()

        def output_type_handler(cursor: Any, metadata: Any) -> Any:
            if metadata.type_code is self.oracledb.DB_TYPE_BLOB:
                return cursor.var(self.oracledb.DB_TYPE_LONG_RAW, arraysize=cursor.arraysize)
            return None

        cur.outputtypehandler = output_type_handler
        return cur

    def initialize_database(self, **kwargs: Any) -> None:
        """
        Ensure that the `embeddings` and `embeddings_index` tables exist.
        """
        cur = self._cursor()
        try:
            cur.execute(
                "SELECT table_name FROM user_tables"
                " WHERE table_name IN ('EMBEDDINGS', 'EMBEDDINGS_INDEX')"
            )
            existing_tables = {r[0] for r in cur.fetchall()}

            if "EMBEDDINGS" not in existing_tables:
                cur.execute(CREATE_EMBEDDINGS_TABLE_SQL)
                logger.debug("Created 'embeddings' table in Oracle.")

            if "EMBEDDINGS_INDEX" not in existing_tables:
                cur.execute(CREATE_EMBEDDINGS_INDEX_TABLE_SQL)
                logger.debug("Created 'embeddings_index' table in Oracle.")
        except self.oracledb.DatabaseError as e:
            if _error_code(e) == _INSUFFICIENT_PRIVILEGES_CODE:
                raise ValueError(
                    "The Oracle user does not have permission to create "
                    "the required tables ('embeddings', 'embeddings_index'). "
                    "Please ask your database administrator to grant CREATE TABLE privileges."
                ) from e
            raise
        finally:
            cur.close()

    def close(self) -> None:
        """Close the database connection."""
        self.conn.close()

    def upsert_embeddings_index(
        self,
        model_name: str,
        detector_backend: str,
        aligned: bool,
        l2_normalized: bool,
        index_data: bytes,
    ) -> None:
        """
        Upsert embeddings index into Oracle.
        Args:
            model_name (str): Name of the model.
            detector_backend (str): Name of the detector backend.
            aligned (bool): Whether the embeddings are aligned.
            l2_normalized (bool): Whether the embeddings are L2 normalized.
            index_data (bytes): Serialized index data.
        """
        update_query = """
            UPDATE embeddings_index
            SET index_data = :index_data, updated_at = SYSTIMESTAMP
            WHERE model_name = :model_name AND detector_backend = :detector_backend
                AND align = :align AND l2_normalized = :l2_normalized
        """
        insert_query = """
            INSERT INTO embeddings_index (model_name, detector_backend, align, l2_normalized, index_data)
            VALUES (:model_name, :detector_backend, :align, :l2_normalized, :index_data)
        """
        params = {
            "model_name": model_name,
            "detector_backend": detector_backend,
            "align": int(aligned),
            "l2_normalized": int(l2_normalized),
            "index_data": index_data,
        }
        cur = self._cursor()
        try:
            # bytes are bound as RAW by default, which is limited to 32 KB
            cur.setinputsizes(index_data=self.oracledb.DB_TYPE_BLOB)
            cur.execute(update_query, params)
            if cur.rowcount == 0:
                cur.setinputsizes(index_data=self.oracledb.DB_TYPE_BLOB)
                cur.execute(insert_query, params)
            self.conn.commit()
        except Exception:
            self.conn.rollback()
            raise
        finally:
            cur.close()

    def get_embeddings_index(
        self,
        model_name: str,
        detector_backend: str,
        aligned: bool,
        l2_normalized: bool,
    ) -> bytes:
        """
        Get embeddings index from Oracle.
        Args:
            model_name (str): Name of the model.
            detector_backend (str): Name of the detector backend.
            aligned (bool): Whether the embeddings are aligned.
            l2_normalized (bool): Whether the embeddings are L2 normalized.
        Returns:
            bytes: Serialized index data.
        """
        query = """
            SELECT index_data
            FROM embeddings_index
            WHERE model_name = :1 AND detector_backend = :2 AND align = :3 AND l2_normalized = :4
        """
        cur = self._cursor()
        try:
            cur.execute(query, (model_name, detector_backend, int(aligned), int(l2_normalized)))
            result = cur.fetchone()
        finally:
            cur.close()

        if result:
            return bytes(result[0])
        raise ValueError(
            "No Embeddings index found for the specified parameters "
            f" {model_name=}, {detector_backend=}, {aligned=}, {l2_normalized=}. "
            "You must run build_index first."
        )

    def insert_embeddings(self, embeddings: List[Dict[str, Any]], batch_size: int = 100) -> int:
        """
        Insert multiple embeddings into Oracle.
        Args:
            embeddings (List[Dict[str, Any]]): List of embeddings to insert.
            batch_size (int): Number of embeddings to insert per batch.
        Returns:
            int: Number of embeddings inserted.
        """
        if not embeddings:
            raise ValueError("No embeddings to insert.")

        query = """
            INSERT INTO embeddings (
                img_name,
                face,
                face_shape,
                model_name,
                detector_backend,
                aligned,
                l2_normalized,
                embedding,
                face_hash,
                embedding_hash
            )
            VALUES (:1, :2, :3, :4, :5, :6, :7, :8, :9, :10)
        """

        values = []
        for e in embeddings:
            face = e["face"]
            face_shape = json.dumps(list(face.shape))
            face_bytes = face.astype(np.float32).tobytes()
            face_json = json.dumps(face.tolist())

            # the same bytes are stored and hashed
            embedding_bytes = struct.pack(f'<{len(e["embedding"])}d', *e["embedding"])

            # uniqueness is guaranteed by face hash and embedding hash
            face_hash = hashlib.sha256(face_json.encode()).hexdigest()
            embedding_hash = hashlib.sha256(embedding_bytes).hexdigest()

            values.append(
                (
                    e["img_name"],
                    face_bytes,
                    face_shape,
                    e["model_name"],
                    e["detector_backend"],
                    int(e["aligned"]),
                    int(e["l2_normalized"]),
                    embedding_bytes,
                    face_hash,
                    embedding_hash,
                )
            )

        blob = self.oracledb.DB_TYPE_BLOB
        cur = self._cursor()
        try:
            for i in range(0, len(values), batch_size):
                # face and embedding exceed the 32 KB limit of RAW binds
                cur.setinputsizes(None, blob, None, None, None, None, None, blob, None, None)
                cur.executemany(query, values[i : i + batch_size])
                # commit for every batch
                self.conn.commit()
            return len(values)
        except self.oracledb.IntegrityError as e:
            self.conn.rollback()
            if _error_code(e) != _UNIQUE_VIOLATION_CODE:
                raise
            if len(values) == 1:
                logger.warn("Duplicate detected for extracted face and embedding.")
                return 0
            raise DuplicateEntryError(
                f"Duplicate detected for extracted face and embedding columns in {i}-th batch"
            ) from e
        finally:
            cur.close()

    def fetch_all_embeddings(
        self,
        model_name: str,
        detector_backend: str,
        aligned: bool,
        l2_normalized: bool,
        batch_size: int = 1000,
    ) -> List[Dict[str, Any]]:

        query = """
            SELECT id, img_name, embedding
            FROM embeddings
            WHERE model_name = :1 AND detector_backend = :2 AND aligned = :3 AND l2_normalized = :4
            ORDER BY id ASC
        """

        embeddings: List[Dict[str, Any]] = []

        cur = self._cursor()
        cur.arraysize = batch_size
        try:
            cur.execute(query, (model_name, detector_backend, int(aligned), int(l2_normalized)))
            while True:
                batch = cur.fetchmany(batch_size)
                if not batch:
                    break

                for r in batch:
                    embeddings.append(
                        {
                            "id": int(r[0]),
                            "img_name": r[1],
                            "embedding": _decode_embedding(r[2]),
                            "model_name": model_name,
                            "detector_backend": detector_backend,
                            "aligned": aligned,
                            "l2_normalized": l2_normalized,
                        }
                    )
        finally:
            cur.close()
        return embeddings

    # criteria arguments are not required, because all embeddings are stored in a single table
    # pylint: disable=unused-argument
    def fetch_embedding(
        self,
        identity_id: Union[str, int],
        model_name: str = "VGG-Face",
        detector_backend: str = "opencv",
        aligned: bool = True,
        l2_normalized: bool = False,
    ) -> Optional[Dict[str, Any]]:
        """
        Fetch a single embedding record with its vector from Oracle. Criteria arguments
            are ignored, because a single table stores the embeddings of all criteria, and
            the record itself carries the criteria that it was registered with.
        Args:
            identity_id (str or int): ID of the record to fetch.
            model_name (str): Name of the model. Ignored.
            detector_backend (str): Name of the detector backend. Ignored.
            aligned (bool): Whether the embeddings are aligned. Ignored.
            l2_normalized (bool): Whether the embeddings are L2 normalized. Ignored.
        Returns:
            Optional[Dict[str, Any]]: Embedding record, or None if no record found for given id.
        """
        query = """
            SELECT id, img_name, model_name, detector_backend, aligned, l2_normalized, embedding
            FROM embeddings
            WHERE id = :1
        """

        cur = self._cursor()
        try:
            cur.execute(query, (int(identity_id),))
            r = cur.fetchone()
        finally:
            cur.close()

        if r is None:
            return None

        return {
            "id": int(r[0]),
            "img_name": r[1],
            "model_name": r[2],
            "detector_backend": r[3],
            "aligned": bool(r[4]),
            "l2_normalized": bool(r[5]),
            "embedding": _decode_embedding(r[6]),
        }

    def search_by_id(
        self,
        ids: Union[List[str], List[int]],
    ) -> List[Dict[str, Any]]:
        """
        Search records by their IDs.
        """
        if not ids:
            return []

        results: List[Dict[str, Any]] = []

        cur = self._cursor()
        try:
            for i in range(0, len(ids), _SEARCH_BY_ID_CHUNK_SIZE):
                chunk = [int(identity_id) for identity_id in ids[i : i + _SEARCH_BY_ID_CHUNK_SIZE]]
                placeholders = ", ".join(f":{j + 1}" for j in range(len(chunk)))
                # we may return the face in the future
                cur.execute(
                    f"SELECT id, img_name FROM embeddings WHERE id IN ({placeholders})"
                    " ORDER BY id ASC",
                    chunk,
                )
                for r in cur.fetchall():
                    results.append(
                        {
                            "id": int(r[0]),
                            "img_name": r[1],
                        }
                    )
        finally:
            cur.close()

        return results
